# Generated by Django 3.2 on 2023-06-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_userprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_position_x',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_position_y',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
